### PR TITLE
Refactor partysocket to use native EventTarget

### PR DESCRIPTION
**Pull request by tom-sherman**
This is an alternative to #171

### CODE REVIEW

**Comment by tom-sherman** [comment]
This has broken the tests because the events `ws` emits aren't the same instance as the jsdom `Event`s and so `dispatchEvent` fails...

Not sure how best to solve this tbh.

**Comment by tom-sherman** [comment]
Also just struggling with these tests in general... Are they marked as flaky because of port in use errors? If so I think I have an idea to fix that.

**Comment by threepointone** [comment]
yeah the tests were disabled because they're flaky af :( 

> This has broken the tests because the events ws emits aren't the same instance as the jsdom Events and so dispatchEvent fails...

ughhh

**Comment by tom-sherman** [comment]
Btw I rebased this branch on #172 and all the tests pass ☺️

**Comment by threepointone** [comment]
image

love to see it

**Comment by threepointone** [comment]
did you mean to leave this as a draft? happy to review and land if you'd like

**Comment by tom-sherman** [comment]
Only because the tests were failing before, ready now!

**Comment by threepointone** [comment]
LFGGGG you're a legend @tom-sherman!

**Comment by brentvatne** [comment]
sadly this breaks support for react-native, where the DOM Event classes are not defined 😭

**Comment by threepointone** [comment]
Oh whoops. Any recommended workarounds/fixes?

**Comment by tom-sherman** [comment]
You can try shimming it: https://www.npmjs.com/package/event-target-shim

React Native are working towards wider support for web standards but I couldn't find an issue for this API.

**Comment by threepointone** [comment]
@brentvatne could you explain how this worked without the shim? https://github.com/expo/todo-sync-example/pull/2 Does expo add the shim?

**Pull request merged**
