### PR TITLE
docs: Update glossary.md to include Durable object definition

### PR DESCRIPTION
**Pull request by prashanthr**
Update glossary to fix empty deep link from [docs page](https://docs.partykit.io/how-partykit-works/#web-server)

### CODE REVIEW

**Review by threepointone — APPROVED** [review]
Thanks!

**Comment by prashanthr** [comment]
@threepointone Any ideas why the `partykit-docs` build is failing? Unfortunately I can't access the vercel build logs.

**Comment by threepointone** [comment]
Bit odd, it's complaining about a missing package, but I haven't made any changes to deps. I'll fix it and land this, don't sweat it.

**Comment by threepointone** [comment]
might be this problem https://twitter.com/ericclemmons/status/1741993025507623372 / https://github.com/lovell/sharp/issues/3870, trying to fix

**Comment by threepointone** [comment]
Yup, looks like that was the problem. Landing this now.

**Comment by prashanthr** [comment]
Awesome, thanks @threepointone 🍻

**Pull request merged**
